### ISSUE TITLE
[Expo 16] Overlaps Issue

### ISSUE THREAD

**Issue by LouisJS** [react-native-community/react-native-modal#138] opened 2018-04-11 13:55 UTC
Since the release of Expo 16, `Modal` in general doesn't work anymore (with Expo).
You can see : 

- https://forums.expo.io/t/actionsheetios-alert-appear-behind-modal/8338/20
- https://github.com/expo/expo/issues/1616

The WebBrowser, ImagePicker, Alert, ect appears behind the Modal.

I just wanted to let you know as we will have to give up on `react-native-modal` library if this issue isn't solve.
Maybe you could contact @brentvatne to know more about the issue and try to find a way to keep `react-native-modal` working with Expo as it is such a primordial library for every react-native user.

**Comment by mmazzarolo** [comment] 2018-04-11 20:25
Since the issue is related to the react-native modal itself I don’t think we can make it work in any way until that issue is fixed.

Anyway, in the last few days I played a bit with a refactoring of this modal for making it 100% JS (without the modal component) so if the Expo issue won’t be fixed soon I’ll probably start working on it on a beta branch.

**Comment by mmazzarolo** [comment] 2018-04-11 20:35
Btw I sent a DM to Brent, thanks for the suggestion

**Comment by mmazzarolo** [comment] 2018-04-18 09:24
It seems that the issue will be fixed soon by expo. 
In the meanwhile I'm opening an issue for discussing a full JS solution.

**Comment by mmazzarolo** [comment] 2018-07-05 18:18
Closing, let's discuss it in the other thread!

**Closed by mmazzarolo** 2018-07-05 18:18 UTC
Labels: question

**Comment by phbn** [comment] 2018-09-14 13:45
Still not working?

**Comment by mmazzarolo** [comment] 2018-09-14 14:01
@phbn The issue is related to the original react-native modal and we can't do much about it.
