### ISSUE TITLE
The statusbar turns white when the modal is open (only on certain devices)

### ISSUE THREAD

**Issue by nidaorhan** [react-native-community/react-native-modal#50] opened 2017-08-01 21:48 UTC
I have a component with status bar set to hidden like this:

```
<View style={ style.container } >
   <StatusBar hidden={true} />

        ...
        
   <Modal isVisible={this.state.isModalVisible}>
     <Text>Modal</Text>   
   </Modal>

</View>
```

When the modal is visible, status bar is hidden but instead there is an empty white block at the top with the exact height of the status bar:

![screenshot](https://user-images.githubusercontent.com/20864001/28848476-bf29b6bc-771b-11e7-857f-a6ef7edf17ad.png)

react-native : 0.45.1
react-native-moda l: 2.5.0
android : 5.1.1

**Comment by mmazzarolo** [comment] 2017-08-02 06:47
Hey @nidaorhan, could you try replacing `react-native-modal` with the [React-Native built in modal](https://facebook.github.io/react-native/docs/modal.html) and see if it has the same issue?

**Comment by nidaorhan** [comment] 2017-08-04 20:09
Yes, I tried, no issues with the React-Native built in modal

**Comment by mmazzarolo** [comment] 2017-08-13 08:11
Sorry for being late, I was on holiday.  
Could you provide an exact code example to reproduce the issue?

**Comment by mmazzarolo** [comment] 2017-08-16 07:19
Closing, feel free to create a new issue if needed 👍

Also, please be aware that I created the following "new issue template" that, if followed correctly, will speed up a lot the issue resolution:

---

### When reporting a bug, please be sure to check if the issue still persists with react-native original modal:
Under the hood `react-native-modal` uses react-native original [Modal component](https://facebook.github.io/react-native/docs/modal.html).  
Before reporting a bug, try swapping `react-native-modal` with react-native original Modal component to check if the problem persists.  

### When reporting a bug, please be sure to include the following:
- [ ] The outcome of the `react-native-modal` swap described above
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `react-native-modal` you're using, and the platform(s) you're running it on (iOS, Android, device)
- [ ] What packages or other dependencies you're using
- [ ] The behavior you expect to see, and the actual behavior


### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

### Please note by far the quickest way to get a new feature is to file a Pull Request.

**Comment by kallrobin** [comment] 2017-09-15 13:03
Hi, i am also dealing with a similar issue
Running: 
    "react-native-modal": "^3.1.0",
    "react-native": "^0.47.2",
    Multiple android versions apk 19-25

When i open my modal i want the Status bar to still be there to keep consistency in the app but when the modal shows the status bar hides. But since the rest of the app is designed to be below the status bar only a white bar is shown in the status bars place.
How am i supposed to disable the modals interference with the status bar?

I tried changing back to the react-native original modal component and the status bar did not hide(animate away upwards).
But when i use the react-native-modal the status bar hides when the modal is activated. I have tried setting StatusBar.setHidden(false) in the onModalShow but it still goes on to hide the status bar.

I hope i have supplied you with enough information to help me, otherwise i'll do my best to try to explain my issue further.

Kind regards

**Comment by mmazzarolo** [comment] 2017-09-15 16:59
@kallrobin thanks a lot, I'm re-opening the issue, could you please provide a bit more info on the subject? 
What device are you using? 
Did you try it on more than one device? 
Are you using an emulator?
What navigation library are you using? 
Also, if you provide a snippet of the js file where you use the modal it would be awesome :)

**Comment by zamponotiropita** [comment] 2017-09-19 23:22
+1

**Comment by EnriqueDev** [comment] 2017-09-26 09:27
I'm dealing with the same issue in RN0.48.

**Comment by mmazzarolo** [comment] 2017-09-26 11:26
Guys, could you please provide the info I asked above?

**Comment by EnriqueDev** [comment] 2017-09-26 13:18
**What device are you using?**
Samsung Galaxy A5 2017 - 6.0.1
Huawey Ascent P8 - Android 6.0

**Did you try it on more than one device?**
Read above

Are you using an emulator?
Read Above 

**What navigation library are you using?**
Read-Native-Router-Flux

**Note**
When trying on android 4.4.2 on a BQ Aquaris 5HD it works properly.

**Comment by mmazzarolo** [comment] 2017-09-26 14:11
@EnriqueDev that's exactly what I suspected :(
I'll try to investigate, thanks for the info

**Comment by kallrobin** [comment] 2017-09-26 14:17
Hi!
Sorry for the delayed response.
But i can also confirm that its a problem with specific devices. So far i only encounter this problem om the nexus5.
All of my android tests had been on emulated devices.
And the navigation lib i'm using is react-navigation.
I decided that atleast on the app i'm developing now i'll just leave it and sadly users on the nexus 5 will have that white bar on top. Might try and do something about it later when i don't have so much more important things to do.

**Comment by mmazzarolo** [comment] 2017-09-26 14:19
That's weird, I'm not having the issue on the N5 on simulator...

**Comment by kallrobin** [comment] 2017-09-26 14:22
Wow. That's strange!
That might indicate it has to do with some specific combination of libraries that i'm using together with the N5.

**Comment by gasparteixeira** [comment] 2017-09-27 00:27
Hey Guys, 

I had same problem. I just put this` transparent={false}` props and everything is working on Android.

**Comment by Stophface** [comment] 2017-09-28 08:09
@gasparteixeira where exactly do you pass these props?

**Comment by mmazzarolo** [comment] 2017-09-28 08:17
@Stophface in the `StatusBar` component i guess... 🤔

**Comment by gasparteixeira** [comment] 2017-09-28 11:35
@mmazzarolo  and @Stophface  I put it in `Modal` from react-modal-native
```
<Modal
            isVisible={this.state.isModalVisible}
            backdropColor='transparent'
            transparent={false}
            style={styles.modalContent}>
```

**Comment by mmazzarolo** [comment] 2017-10-13 07:11
Can anyone confirm @gasparteixeira solution?

**Comment by zmartell** [comment] 2017-10-14 06:28
@mmazzarolo doesn't seem to work.

**Comment by mmazzarolo** [comment] 2017-10-18 15:19
Might be related to [this issue](https://github.com/facebook/react-native/issues/9090#issuecomment-337624981)

**Comment by kallrobin** [comment] 2017-10-19 08:45
@gasparteixeira I understand why that seems to work. But it's not fixing the issue really.
All you are doing is making the background not transparent and by default it's white. So now the status bar looks "fine" but now i can't see the background (eg. the app).
Although there might be something there to look at. I just can't seem to find some solution.

**Comment by gasparteixeira** [comment] 2017-10-19 22:15
@kallrobin you right! I made an "ugly" solution. It worked for me and maybe it was not the right way....  I also did another weird thing. I set the background transparent and declare a View with background color inside this!

**Comment by Norfeldt** [comment] 2017-10-21 11:16
@gasparteixeira Would you mind sharing your "working" code?

**Comment by ruoyuruoshui** [comment] 2017-10-22 03:55
@Norfeldt i have the same problem, this is my mode

`
<Modal
                isVisible={this.state.selectorVisible}
                backdropColor={'#303437'}
                backdropOpacity={0.5}
                style={{marginHorizontal: 0, marginVertical: 0, justifyContent: 'flex-end',}}
                animationIn={'slideInUp'}
                animationInTiming={500}
                animationOutTiming={500}
                backdropTransitionInTiming={500}
                backdropTransitionOutTiming={500}
                hideOnBack={true}
                onBackButtonPress={this.onSelectorClosed.bind(this)}
                onModalHide={() => {
                    this.state.selectorVisible = false
                }}
            >
....
</Modal>`

**Comment by ruoyuruoshui** [comment] 2017-10-22 03:56
I have the same problem, this is my code

` <Modal
                isVisible={this.state.selectorVisible}
                backdropColor={'#303437'}
                backdropOpacity={0.5}
                style={{marginHorizontal: 0, marginVertical: 0, justifyContent: 'flex-end',}}
                animationIn={'slideInUp'}
                animationInTiming={500}
                animationOutTiming={500}
                backdropTransitionInTiming={500}
                backdropTransitionOutTiming={500}
                hideOnBack={true}
                onBackButtonPress={this.onSelectorClosed.bind(this)}
                onModalHide={() => {
                    this.state.selectorVisible = false
                }}
            >
                ...
            </Modal>`

**Comment by gasparteixeira** [comment] 2017-10-22 13:37
Hello @Norfeldt 
I did an experience to show you what I did. Let me know if it worked for you! 

Please check out this experience on github: 
https://github.com/gasparteixeira/react-navite-modal-exp or take a look at the only edited file
//App.js
`import React from 'react';
import { StyleSheet, Text, View, TouchableOpacity, StatusBar} from 'react-native';
import Modal from 'react-native-modal'

export default class App extends React.Component {
  state = {
    isModalVisible: false,
    barStyle: 'dark-content'
  }
  _showModal = () => this.setState({ isModalVisible: true, barStyle: 'light-content' })

  _hideModal = () => this.setState({ isModalVisible: false, barStyle: 'dark-content' })
  render() {
    return (
      <View style={styles.container}>
        <StatusBar translucent barStyle={this.state.barStyle}/>
        <TouchableOpacity onPress={() => this._showModal()}>
          <Text>Show Modal</Text>
        </TouchableOpacity>
        <Modal
          isVisible={this.state.isModalVisible}
          backdropColor='transparent'
          transparent={false}
          style={styles.modalWindow}>
          <View style={styles.modalContent}>
            <TouchableOpacity onPress={() => this._hideModal()}>
              <Text style={{color: 'white'}}>Close</Text>
            </TouchableOpacity>
            <Text style={{color: 'white'}}>Modal full!</Text>
          </View>
        </Modal>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalWindow: {
    margin: 0,
  },
  modalContent: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    alignItems: 'center',
    justifyContent: 'center',
  }
});
`
To scan my "working" code here is the expo link: 
https://exp.host/@gasparteixeira/modal-exp

![modalandroid](https://user-images.githubusercontent.com/390818/31862484-43cea562-b71d-11e7-9813-84448aaea7fa.gif)
![modalios](https://user-images.githubusercontent.com/390818/31862485-440fc34e-b71d-11e7-8b95-3ea58b214867.gif)

**Comment by webraptor** [comment] 2017-12-20 14:49
Can be fixed with https://github.com/facebook/react-native/issues/7474#issuecomment-288814366

**Comment by toussa** [comment] 2018-01-25 17:22
@webraptor well, this workaround does not work with Expo.

By the way, I can confirm the problem with react-native: 0.50.3, expo and Google Nexus 9 - 5.0.0 (API 21)

**Comment by mmazzarolo** [comment] 2018-01-29 18:48
For everyone having the issue, could you try placing the modal on the root of you app and see if it still shows the white bar?

**Comment by mmazzarolo** [comment] 2018-01-30 07:33
I also had the same issue using [react-native-material-dropdown](https://github.com/n4kz/react-native-material-dropdown) (which uses the native modal), see [this related issue](https://github.com/n4kz/react-native-material-dropdown/issues/62)

**Comment by toussa** [comment] 2018-01-30 10:01
@mmazzarolo I did the test (modal on Root component, outside of navigator) => same issue :disappointed:

**Comment by mmazzarolo** [comment] 2018-01-30 10:20
Ok, I gave it another try and the issue is indeed related to React-Native modal.  
The following code has the same "white statusbar" issue, caused by `transparent={true}`:  

```
import React from "react";
import { Modal, View } from "react-native";

export default class Root extends React.Component<{}> {
  render() {
    return (
      <View style={{ flex: 1 }}>
        <Modal transparent={true} style={{ flex: 1 }}>
          <View style={{ backgroundColor: "blue", flex: 1 }} />
        </Modal>
      </View>
    );
  }
}
```  

I'm trying the code above on different devices before opening an issue on the official react-native/expo repo.

**Comment by listenzz** [comment] 2018-04-25 02:56
I had fix this issue

https://github.com/listenzz/react-native-modal-translucent

**Comment by GollyJer** [comment] 2018-05-28 03:36
@wkoutre Very cool!  Nice work.
Hopefully someone on the core team can use what you've done to get this into the native modal.

We're using Expo so I'm unable to get your fix because I can't `react-native link`.

**Comment by wkoutre** [comment] 2018-06-07 01:57
@GollyJer It can always be manually linked. 

Haven't used Expo in over a year so I can't speak to the process/possibility but.. react-native link is finicky as it is, so I usually either use Cocoapods (if supported) or manually link.

**Comment by alex-mironov-ynd** [comment] 2018-07-02 08:52
Why is this issue closed? It's still there.

**Comment by alex-mironov** [comment] 2018-07-02 08:53
Why is this issue closed? It's still there.

**Comment by mmazzarolo** [comment] 2018-07-02 08:57
@alex-mironov because unfortunately we cannot do too much about it since [it's a RN issue](https://github.com/facebook/react-native/issues/9090#issuecomment-337624981) 😞

**Comment by Evangelione** [comment] 2018-10-25 02:08
> I had fix this issue
> 
> https://github.com/listenzz/react-native-modal-translucent

nice!

**Comment by jiangbophd** [comment] 2018-11-09 16:00
so bad, the issue still there

**Comment by jpamarohorta** [comment] 2018-11-29 15:11
Why is this issue closed?

@listenzz package indeed fixes it but, isn't this still a bug?

**Comment by mmazzarolo** [comment] 2018-11-29 15:42
> Why is this issue closed?

Because, as far as I know, it's caused by RN own Modal, and not by `react-native-modal`. 
I'll reopen it, but if this is still the case the issue should be addressed directly in react-native :(

**Comment by jpamarohorta** [comment] 2018-11-29 15:43
Oh I understand. If that's the case then this one should be closed. You are right sorry.

**Comment by mmazzarolo** [comment] 2018-11-29 15:54
No worries, here's the issue: https://github.com/facebook/react-native/issues/9090#issuecomment-337624981

**Closed by mmazzarolo** 2018-11-29 15:54 UTC
Labels: android-only, bug

**Comment by RichardLindhout** [comment] 2019-02-12 22:19
New issue: https://github.com/facebook/react-native/issues/20623

**Comment by swayok** [comment] 2019-05-16 13:11
> StatusBar put inside Modal wrap from a View worked for me
> 
> ```
>   <Modal>
>     <View>
>       <StatusBar backgroundColor="rgba(0,0,0,0.7)"  barStyle="light-content"/>
>     </View>
>   </Modal>
> ```

Note for `react-native-elements` `Overlay` component: only `backgroundColor` works while `barStyle` has no effect and always `light-content`. 
Tested in simulator with android 8.1 and on Xiaomi Mi5 8.1

**Comment by pinguo-zhouwei** [comment] 2019-06-18 10:09
a better solution for this issue: https://github.com/23mf/react-native-translucent-modal

**Comment by swayok** [comment] 2019-06-18 10:21
> a better solution for this issue: https://github.com/23mf/react-native-translucent-modal

I'm using react-native-elements Ovarlay component so it does not solve my case easily =( 
Maybe I should reconsider this choice.

**Comment by RichardLindhout** [comment] 2019-06-24 10:49
Just use the portal branch of this modal ;)

**Comment by fangasvsass** [comment] 2019-06-28 05:47
the issue still  react native 0.59.9

**Comment by TheNerdGuyLulu** [comment] 2019-07-13 02:58
A possible work around...
I took a printscreen and "picked" the color.

![asas](https://user-images.githubusercontent.com/20543676/61166198-e8380500-a521-11e9-8e7c-3d883850f6b1.png)

Then inside the modal with the StatusBar component I assigned the background color with the previous value.
```
<Modal>
    <View>
          <StatusBar barStyle="dark-content" backgroundColor={'#4A4B4D'} />  // Assign the background 
          <Text>Test</Text>
    </View>
</Modal>
```
 And... voilá.

![asdasd](https://user-images.githubusercontent.com/20543676/61166227-5d0b3f00-a522-11e9-8bd7-a26ecae471a3.png)

It's not perfect when it comes to open and close transition, but far better than all white status bar in my opinion.

**Comment by headfire94** [comment] 2019-08-30 14:42
Possible workaround:

1. Create simple modal component wrapped with `View` instead of native `Modal`.
2. Use https://github.com/headfire94/react-native-gateway to render modal on top of everything (above statusBar, content, tabBat and so on), it works just like react Portal.
3. apply back handler from `react-navigation-backhandler` to allow close it on hardware `back` button on Android

Modal works just like native in this case (If i'm not missing something)

**Comment by sidlu-company** [comment] 2019-08-31 02:46
> I had fix this issue
> 
> https://github.com/listenzz/react-native-modal-translucent

perfect!

**Comment by Daniyal857** [comment] 2019-10-04 11:37
> a better solution for this issue: https://github.com/23mf/react-native-translucent-modal
> 
> <img alt="after-pop1" width="50%" height="70%" src="https://user-images.githubusercontent.com/8786349/59673702-52e07400-91f4-11e9-857d-86baa9719096.png">

a perfect one

**Comment by mstosio** [comment] 2019-10-31 09:38
If you still got this bug and you are making Modal visible accrding to some state you should consider using:

const [isVisible, setModalVisible] = useState(false);

	 const handleModalOpen = ()=> {
	 	StatusBar.setHidden(!isVisible);
	 	setTimeout(() => {
			setModalVisible(isVisible);
	 	}, 50);
         };

setTimeout make it async and prevents from this Bug.

**Comment by wenkangzhou** [comment] 2019-11-06 11:29
Has any progerss?

**Comment by viktor992** [comment] 2019-12-10 01:46
In my case, the solution was to use the `coverScreen` and `deviceHeight` props in the following way:


    <Modal
      isVisible={isVisible}
      backdropOpacity={0.9}
      backdropColor="white"
      animationIn="fadeIn"
      animationOut="fadeOut"
      coverScreen={false}
      deviceHeight={Dimensions.get('screen').height}
    >
        {/* CONTENT */}
    </Modal>

**Comment by shels107** [comment] 2019-12-12 11:14
@viktor992 thanks, it's work for me

**Comment by rdgomt** [comment] 2020-01-03 01:40
Didn't work for me :(

**Comment by ifsnow** [comment] 2020-04-01 23:15
`statusBarTranslucent` property has been added to Modal of RN 0.62

```js
<Modal ... statusBarTranslucent>...</Modal>
```

I think this problem has been solved. :)

**Comment by sauhardar** [comment] 2020-06-06 03:03
How can I add the `statusBarTranslucent` prop to `react-native-modal`'s `Modal` component?

**Comment by iroslehu** [comment] 2020-06-25 20:22
> Hey Guys,
> 
> I had same problem. I just put this` transparent={false}` props and everything is working on Android.

Thanks, it works for me.

**Comment by yalcinozer** [comment] 2020-08-24 08:33
> `statusBarTranslucent` property has been added to Modal of RN 0.62
> 
> ```js
> <Modal ... statusBarTranslucent>...</Modal>
> ```
> 
> I think this problem has been solved. :)

How did I miss that? Thanks bro.

**Comment by rayj10** [comment] 2020-09-09 07:40
Anyone experiencing this?
I made my app full screen on Android, the modal is clashing with the hidden android nav bar and status bar
this happens on most android devices with soft nav bar for me, but this screenshot is from emulator (Nexus 5 API 27)

any pointers would be awesome
![Screenshot_1599637240](https://user-images.githubusercontent.com/38281328/92568957-1f32b380-f2aa-11ea-8f4a-a7d035309fb5.png)

**Comment by gregogalante** [comment] 2020-12-03 13:41
@rayj10 have you found a solution for the problem?

**Comment by Linkitsoft** [comment] 2021-03-06 13:13
> I have a component with status bar set to hidden like this:
> 
> ```
> <View style={ style.container } >
>    <StatusBar hidden={true} />
> 
>         ...
>         
>    <Modal isVisible={this.state.isModalVisible}>
>      <Text>Modal</Text>   
>    </Modal>
> 
> </View>
> ```
> 
> When the modal is visible, status bar is hidden but instead there is an empty white block at the top with the exact height of the status bar:
> 
> ![screenshot](https://user-images.githubusercontent.com/20864001/28848476-bf29b6bc-771b-11e7-857f-a6ef7edf17ad.png)
> 
> react-native : 0.45.1
> react-native-moda l: 2.5.0
> android : 5.1.1

   
        <Modal
          visible={showModal}
           backdropColor='#ee535d' <-- Add this
            transparent={false} <-- Add this
            statusBarTranslucent <-- Add this
   
        >
            ..
            .
            .
        </Modal>

**Comment by salyndev0** [comment] 2021-11-28 07:07
### 11/2021

### **To anyone that facing this if you tried all from top solutions but doesn't look like what you think then here try mine**. 

**- Because I used stack in a tab so this is what it look like:**

<img src="https://user-images.githubusercontent.com/66520542/143732189-03d5995c-51bc-4d50-a4bc-b00403dd1856.png" width="50%" height="50%">

**The code:**
```
<Modal 
        statusBarTranslucent    //Add this if you trying to Make the StatusBarTranslucent like mine.
        backdropOpacity={0.5}
        backdropColor="#000"
        coverScreen={true}
        deviceHeight={Dimensions.get('screen').height}
        animationIn={'slideInUp'}
        .......   //Other option you want to use.
>
//Your Content
</Modal>
```

But if you remove this: ` deviceHeight={Dimensions.get('screen').height}`
This's what is look like:
<img src="https://user-images.githubusercontent.com/66520542/143732356-31a2f912-2f05-40ec-9ef0-1e00f5e3d6b3.png" width="50%" height="50%">
**Did you see that weird gray thing at the bottom ? jesus**

**Or you follow  someone above and see this:**
 `coverScreen={false}`
### You will see nothing
So keep in mind  `coverScreen={true}` must be _TRUE_


**And because I use tab with stack to present the modal like in the docs they have this:** 
`screenOptions={{presentation: 'transparentModal'}` 
and 
`<StatusBar translucent backgroundColor="transparent" />`
in the stack screen
My project structure look like this 

- Tab
- - Stack Navigation
- - - Home Screen
- - - Modal Screen(container real modal)

So with those too setup above I can have a modal transparent background so when I press tabButton
I can change to the Modal Screen with navigation and the Home Screen will show behind the modal with the transparent StatusBar . Show when it come up with modal screen it look beautiful.

**Comment by abdulrehmanicm** [comment] 2022-04-05 10:18
{/* <StatusBar backgroundColor={visibleModal? "rgba(0,0,0,0.7)": 'transparent'}  barStyle={visibleModal ?  'light-content' : 'dark-content'} /> */}

**Comment by nkutechologies** [comment] 2022-08-06 15:20
> backdropColor='#ee535d' <-- Add this
>         transparent={false} <-- Add this
>         statusBarTranslucent <-- Add this

this works for me Thanks

**Comment by cocoa-1012** [comment] 2022-10-04 09:28
Hi, there.
I've made a Android app without statusbar. But when I show the modal, it includes statusbar and it makes the app is poor.

Is there any way to hide the statusbar in modal? 
I doesn't mean transparent, I need to hide the statusbar.

Thanks.

**Comment by lucas-ssv** [comment] 2022-10-17 18:58
Hi there.
There's a modal option that makes this. Try `statusBarTranslucent`:

`  <Modal
        animationType="fade"
        transparent={true}
        statusBarTranslucent
        visible={isVisible}
   ></Modal>`

**Comment by PramelaDevi-S** [comment] 2023-01-19 12:26
> `statusBarTranslucent` property has been added to Modal of RN 0.62
> 
> ```js
> <Modal ... statusBarTranslucent>...</Modal>
> ```
> 
> I think this problem has been solved. :)

Thank you, it's helpful :)

**Comment by goxr3plus** [comment] 2023-04-17 13:37
> 

Unbelievable this was the solution . Unbelievable i was searching for 1.5 year i love you !!! **I will cry lol**

I have no words no joking . 

I am giving you a full example guyz:

```
				<Modal
			      ...
					useNativeDriverForBackdrop
					hideModalContentWhileAnimating
					style={{ maxWidth: windowWidth, marginLeft: 0, marginRight: 0, marginTop: 0, marginBottom: 0 }}
					coverScreen={false}
					deviceHeight={screenHeight}
				>
```

**Comment by goxr3plus** [comment] 2023-04-17 14:17
You will find some problems though if you stuck 2 modals on top of each other etc so you have to be careful with the above solution .

**Comment by CAglarBilkent** [comment] 2024-01-16 05:19
@cocoa-1012 
Were you able to find a solution? I am facing the same issue. This is so weird

**Comment by Jainam1224** [comment] 2024-05-07 17:22
When using statusBarTranslucent then also in some apps it has some weird gap at the top and bottom of the phone screen and the background is visible. Any final solve for this issue?

**Comment by Mohitkumawat6260** [comment] 2024-05-23 12:28
> > StatusBar put inside Modal wrap from a View worked for me
> > ```
> >   <Modal>
> >     <View>
> >       <StatusBar backgroundColor="rgba(0,0,0,0.7)"  barStyle="light-content"/>
> >     </View>
> >   </Modal>
> > ```
> 
> Note for `react-native-elements` `Overlay` component: only `backgroundColor` works while `barStyle` has no effect and always `light-content`. Tested in simulator with android 8.1 and on Xiaomi Mi5 8.1

> I have a component with status bar set to hidden like this:
>  add this line style.xml

            <item name="android:windowFullscreen">true</item>

**Comment by Mohitkumawat6260** [comment] 2024-05-23 12:28
> `statusBarTranslucent` property has been added to Modal of RN 0.62
> 
> ```js
> <Modal ... statusBarTranslucent>...</Modal>
> ```
> 
> I think this problem has been solved. :)

> I have a component with status bar set to hidden like this:
>  add this line style.xml

            <item name="android:windowFullscreen">true</item>

**Comment by pammu453** [comment] 2025-05-23 07:11
<Modal
                    animationType="slide"
                    transparent={false}
                    visible={modalVisible}
                    onRequestClose={toggleModal}
                    statusBarTranslucent={true}  // this fixed to me

                >
