### ISSUE TITLE
onBackdropPress does not work on 11.3.0

### ISSUE THREAD

**Issue by jslok** [react-native-community/react-native-modal#338] opened 2019-07-30 22:23 UTC
## Environment

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    Memory: 19.84 GB / 31.94 GB
  Binaries:
    Node: 12.7.0
    Yarn: 1.17.3
    npm: 6.9.0
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245
## Versions

- Android:
- iOS:
- react-native-modal: 11.3.0
- react-native: 60.4
- react:16.8.6

## Description

With the new 11.3.0, onBackdropPress does not work. I am not using a custom backdrop. Downgraded to 11.2.0 and it works again.

**Comment by kenyontu** [comment] 2019-07-30 23:33
Thanks for the report @jslok 
I did some debugging and this happens because the change introduced in 11.3.0 doesn't make the backdrop touchable when the Modal prop `coverScreen` is set to true (which is the default value).

I will make a PR when I get free time, unless someone does it first.

**Comment by mmazzarolo** [comment] 2019-07-31 06:52
Thanks @jslok 🙏  
Just sent #339 ... I can't test it right now though, anyone willing to check it?

**Comment by jslok** [comment] 2019-07-31 07:06
Wow that was fast. I just reported it this afternoon.

11.3.1 works great for me. Thanks!

**Comment by mmazzarolo** [comment] 2019-07-31 08:38
All thanks to @kenyontu :)

**Comment by diegorodriguesvieira** [comment] 2019-09-02 12:40
On iPhone XS Max is still not working.

**Comment by redbluenat** [comment] 2019-09-03 14:27
for me it doesn't work as well iPhoneX

**Comment by rewieer** [comment] 2019-09-03 18:12
It's broken, just tested it.

**Comment by rewieer** [comment] 2019-09-04 07:08
Seems to be fixed in 11.3.1. Make sure you don't have a view with 100% height/width above the backdrop, in which case the touch event wont be caught by the underlying backdrop.

**Closed by rewieer** 2019-09-04 07:08 UTC
Labels: bug

**Comment by redbluenat** [comment] 2019-09-04 07:57
@rewieer I have simple view inside modal and still doesn't work, for Android works okay but for IOS press on the backdrop, doesn't work. I have IPhoneX - 12.4 and the newest modal version. Why yesterday you said it is broken and today it is working for you? Can you provide code which didn't work for you and this one which works for you today?

**Comment by rewieer** [comment] 2019-09-04 08:02
@redbluenat Yesterday I was using RN 11.1.0 and noticed the very same problem. Today I upgraded to 13.1.0 and it wasn't working either. After careful debugging I realized I had a view that spawned all above the backdrop, such that events wouldn't propagate to the backdrop. Fixed it and it reworked again.

Can you provide some sample repository of a code that doesn't work ? That'd be easier for me to try and debug what's happening. Of course if you can try to debug and find the root cause, you can either point me to the problem or submit a PR.

**Comment by zmnv** [comment] 2020-05-26 20:51
If `coverScreen`  is `false` then `onBackButtonPress` in android doesn't work.

```
"react-native": "0.61.5",
"react-native-modal": "11.5.6",
```

**Comment by thiagomorales** [comment] 2020-05-27 19:22
Same here, with 11.5.6 version.
When using `converScreen={false}` or have a custom backdrop (simple view) the `onBackButtonpress` doesn't work.

To get work i needed to do a workaround like this:

`customBackdrop={
        <TouchableWithoutFeedback
          onPress={dismiss}
        >
          <View
            style={{
              flex: 1,
              backgroundColor: '#000',
              marginTop: 56,
            }}
          />
        </TouchableWithoutFeedback>
      }`

**Comment by yjb94** [comment] 2020-10-15 07:20
I just managed to make a PR for this. In urgent cases, you can just get code from my repository

**Comment by yjb94** [comment] 2020-10-15 11:49
Finally... I fixed this bug in #485. Hope my PR is merged soon.

**Comment by cicconewk** [comment] 2020-12-02 14:44
> 
> 
> Same here, with 11.5.6 version.
> When using `converScreen={false}` or have a custom backdrop (simple view) the `onBackButtonpress` doesn't work.
> 
> To get work i needed to do a workaround like this:
> 
> ```
> customBackdrop={
>   <TouchableWithoutFeedback onPress={dismiss}>
>     <View
>       style={{
>         flex: 1,
>         backgroundColor: '#000',
>         marginTop: 56,
>       }}
>     />
>   </TouchableWithoutFeedback>
> }
> ```

Thanks! this worked for me.

**Comment by gruckion** [comment] 2021-08-07 17:18
RELOAD the iOS emulator! This happened to me I tried loads of stuff, then noticed it's fine for my friend. Reloaded the emulator and it's fine. WTF nice waste of 2 hours...

**Comment by Kasik-D** [comment] 2023-01-25 09:01
@gruckion Thx so much
