### ISSUE TITLE
undefined is not an object (evaluating '_this.backdropRef.transitionTo')

### ISSUE THREAD

**Issue by graphee-gabriel** [react-native-community/react-native-modal#42] opened 2017-07-20 13:41 UTC
Hello I'm using expo,

After updating to SDK 19 with react-native 46  I get the following message when opening the modal:

`undefined is not an object (evaluating '_this.backdropRef.transitionTo')`

Any idea?

**Comment by JuniusAng** [comment] 2017-07-21 07:40
got the same issue in android, 
"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
"react-native-modal": "^2.3.2",

I think the problem happened here:
```
_close = async () => {
    this.backdropRef.transitionTo({ opacity: 0 }, this.props.backdropTransitionOutTiming);
   ...
  };
```

any quick fix for this?

**Comment by KeabetsweFx** [comment] 2017-07-21 07:53
I've just upgrade to expo SDK 19 as well and I'm seeing the same error, it was working fine on expo SDK 18.

**Comment by mmazzarolo** [comment] 2017-07-21 08:26
Umh too bad, I never used Expo and I don't even know where to start 😭 

I'll give it a shot as soon as I have some free time.  

Does Expo SDK have a changelog available somewhere? It might be a good starting point.

**Comment by marc314** [comment] 2017-07-21 17:20
Same issue for me as well. RedBox. On dismissal, the overlay is missing but the modal renders.

**Comment by mmazzarolo** [comment] 2017-07-22 13:06
I still have to take a look at it, hope I'll have some free time this evening.  
  
Also, help on the matter would be super-apreciated (it is indeed a breaking change caused by the last version of React-Native) 🌟

**Comment by mmazzarolo** [comment] 2017-07-24 06:57
I just had the chance to test it on a clean react-native 0.46 install and it is working fine for me, so it might really be related to Expo.  

Anyone else having the issue but **not** using Expo?

**Comment by cosmocoder** [comment] 2017-07-24 08:12
I am seeing this issue as well with Expo, and get the React Native error screen. On dismissing the error screen the modal is visible but without the backdrop.

**Comment by mmazzarolo** [comment] 2017-07-24 10:24
I just opened an issue on the [expo repo](https://github.com/expo/expo/issues/404).

**Comment by KeabetsweFx** [comment] 2017-07-27 06:40
Hello guys, quick update just change the version of your npm package from 19.0.0 to 19.0.1 and this should work like before.

**Comment by cosmocoder** [comment] 2017-07-27 07:14
I confirm that Expo SDK 19.0.1 fixes the issue. Thanks for reporting @KeabetsweFx.

**Comment by mmazzarolo** [comment] 2017-07-27 07:26
Thank you @KeabetsweFx and @cosmocoder for the feedback.  

I'm closing the issue, feel free to open another one if needed!

**Closed by mmazzarolo** 2017-07-27 07:26 UTC

**Comment by graphee-gabriel** [comment] 2017-07-27 13:20
Thanks it works perfect :)
