### ISSUE TITLE
Cannot Style like First Example

### ISSUE THREAD

**Issue by Brian-Kaplan** [react-native-community/react-native-modal#15] opened 2017-04-10 18:54 UTC
I love the style and animations of the first gif example (from the left) that you have on the README. I am unable to get the animations to work correctly though. For some reason the default animations do not start from or return to the bottom of the screen like they do in your example. I am able to add a margin to the top so I can center the modal in the screen but when it slides up it doesn't come up from the bottom of the screen. When the modal dismisses it does not slide down past the bottom of the screen. The modal slides down or up for what looks like 100-200 pixels and then pops in or away. It is quite jarring of an animation.

**Comment by mmazzarolo** [comment] 2017-04-10 19:00
Hello there!  
That's weird, animations shouldn't lag at all. 
First of all, what version of React-Native are you using? 
Did you already try the example project in the `example` dir?  (It should give you some hints on the style you can apply!) 
Let me know if it works for you, otherwise just post your code here and I'll try to help as soon as I reach a working pc 💻

**Comment by Brian-Kaplan** [comment] 2017-04-11 13:24
Im using react-native 0.43.1 which requires react 16.0.0-alpha.3

I didn't explicitly try the examples but I did look at the styles and props you pass. I also noticed that there was no documentation for the animation string types.

**Comment by mmazzarolo** [comment] 2017-04-11 13:56
You can take a look at [react-native-animatable](https://github.com/oblador/react-native-animatable) from the available animations.

**Comment by Brian-Kaplan** [comment] 2017-04-11 14:57
Okay thanks for that, I can actually see in the example gifs they show that the animations behave exactly the same way that I see. It doesn't slide up from the bottom of the screen. How did you get it to do that in the first example gif you have. I don't think any of your example code actually matches that specific gif.

**Comment by mmazzarolo** [comment] 2017-04-11 15:43
You are right, it seems that the gif acts differently from how the modal works now 🤔 
I'll take a look at it soon, it might be a regression after a React-Native update.  
Thank you for man :)

**Comment by Brian-Kaplan** [comment] 2017-04-11 15:44
Okay good to see that I'm not going crazy here. Thanks for being so proactive about this. I look forward to seeing what you come up with!

**Comment by mmazzarolo** [comment] 2017-04-15 09:32
@Brian-Kaplan the animations started to behave differently since the react-native-animatable update #10
I tried to backtrack the issue but I've not been able to solve it, it seems to be related to the positioning of the modal content that is not handled correctly since [this react-native-animatable release](https://github.com/oblador/react-native-animatable/releases/tag/v1.0.0).  
I'll try to give it another shot as soon as I have some free time, and if I won't be able to solve it I'll try to ask some help to @oblador (maybe by creating a gif pre and post 1.0.0-release).  

In the meanwhile, if you want to se the animation working correctly just use `react-native-animatable@0.6.1`.

**Comment by g3r4n** [comment] 2017-04-16 14:24
This is because of the 100px value hardcoded in [sliding-entrances](https://github.com/oblador/react-native-animatable/blob/master/definitions/sliding-entrances.js) and [sliding-exits](https://github.com/oblador/react-native-animatable/blob/master/definitions/sliding-exits.js)

**Comment by mmazzarolo** [comment] 2017-04-17 08:31
Wow, @g3r4n great work! Thank you for finding it out! ❤️

**Comment by mmazzarolo** [comment] 2017-04-18 17:55
Landed in [v2.3.2](https://github.com/react-native-community/react-native-modal/releases/tag/v2.3.2).  
Feel free to comment here if needed!

**Closed by mmazzarolo** 2017-04-18 17:55 UTC
Labels: bug

**Comment by Brian-Kaplan** [comment] 2017-04-24 15:50
works like a charm, great work!
