### ISSUE TITLE
Android issue for multiple modals 

### ISSUE THREAD

**Issue by yckbilly1929** [react-native-community/react-native-modal#34] opened 2017-06-16 19:35 UTC
my current version: v2.4.0

Attached the screenshots, on testing with the example.

If we close the modal by pressing android back button instead of the close button, warning message will be shown when we open another modal.

After quick checking on source code, I made the following workaround, but I am not sure if it will break other behaviour.

```
  _close = async () => {
    if (this.state.isVisible) {
      this.backdropRef.transitionTo({ opacity: 0 }, this.props.backdropTransitionOutTiming);
      this.contentRef[this.props.animationOut](this.props.animationOutTiming).then(() => {
        this.setState({ isVisible: false });
        this.props.onModalHide();
      });
    }
  };
```

![test](https://user-images.githubusercontent.com/12884758/27241842-fee17c0a-530c-11e7-88df-ec2700bbe7f7.jpeg)
![test2](https://user-images.githubusercontent.com/12884758/27241843-fee558fc-530c-11e7-84a2-3c33976188ee.jpeg)

**Comment by mmazzarolo** [comment] 2017-06-19 06:48
Hey @ccycecilyip! Thank you for opening the issue and inspecting for the error.  
I'm on vacation right now, so I can't investigate much but... why do you think the issue is arising **only** on back button press? 🤔

**Comment by ccycecilyip** [comment] 2017-06-19 11:43
hi @mmazzarolo 
i logged the function call, and the _close function was called twice
i am thinking about if ```onRequestClose``` is the reason that leads to the issue, as the official doc said that it will be called when user tapped the hardware back button

**Comment by mmerickel** [comment] 2017-09-20 22:05
I do not think this is directly related to the back button. Rather if isVisible gets toggled quickly while transitioning occurs some pretty bad things happen.

1) The refs gets nulled out temporarily which can cause the `backdropRef` and/or `contentRef` to be `null` which causes the promise rejection seen above. Semi-related is this issue https://github.com/facebook/react/issues/4533 but the real issue is just that `_close` is called while already closing and/or opening.

2) The `visible` prop may be set to `false` on the native `Modal` component while transitioning which causes a `setState` was called on an unmounted component error inside the animated `View`.

**Comment by mmerickel** [comment] 2017-09-20 22:08
I've opened https://github.com/react-native-community/react-native-modal/pull/74 for this.

**Comment by mmazzarolo** [comment] 2017-09-22 11:45
@ccycecilyip could you give a shot to @mmerickel solution? Thanks!

**Closed** 2017-11-20 08:45 UTC
Labels: bug, on hold
