### ISSUE TITLE
Modal flickering on closing. 

### ISSUE THREAD

**Issue by jake41** [react-native-community/react-native-modal#268] opened 2019-03-03 11:30 UTC
Modal flickering on closing. Happening both on Ios and Android. Does anyone know a fix for this ?

**Comment by AdrianoRuberto** [comment] 2019-03-04 12:36
[This](https://github.com/react-native-community/react-native-modal#the-modal-flashes-in-a-weird-way-when-animating) may resolve your problems

**Comment by jake41** [comment] 2019-03-04 16:42
I have added  hideModalContentWhileAnimating={true} , but still the flickering is happening.

**Comment by rewieer** [comment] 2019-03-07 06:46
@jake41 can you provide a reproducible repo please ?

**Comment by jake41** [comment] 2019-03-10 15:15
@rewieer  I cant share the repo link unfortunately. 

Here is the params passed to modal : 

`  <Modal
          isVisible={this.state.modalVisible}
          onBackdropPress={async () =>
            await this.setState({ modalVisible: false })
          }
          animationIn="fadeIn"
          animationOut="fadeIn"
          backdropOpacity={0}
          hideModalContentWhileAnimating={true}>
...
...
...
</Modal>`

**Comment by jake41** [comment] 2019-03-14 12:43
Can someone address this please :)  ?

**Comment by rewieer** [comment] 2019-03-14 12:48
Hey, I need a minimal code that produces the output as stated in the [issue template](https://github.com/react-native-community/react-native-modal/blob/master/ISSUE_TEMPLATE.md), without which it's going to be harder for me to spot the cause of the issue

**Comment by P21Marcelo** [comment] 2019-03-20 12:04
hey guys, i have the same problem. on IOS simulator it flickers more than on device. now, on android both device and simulator it flickers the same on opening and closing.
i tried: remove the view and let just ContainerPendencias, and also remove that component and let just the view alone on modal.
 here is my code: 
```
<Modal
                    style={{margin:0}}
                    isVisible={this.state.protestoIsOpen}
                    propagateSwipe={true}
                    hideModalContentWhileAnimating={true}
                    swipeThreshold={90}
                    animationIn="fadeIn"
                    animationOut="fadeIn"
                    swipeDirection={'down'}
                    onSwipeComplete={()=>this.setState({protestoIsOpen:false})}
                    onBackButtonPress={() => NavigationService.goBack()}
                    animationInTiming={770}
                    animationOutTiming={770}
                    useNativeDriver={false}>
                    <View style={styles.modalHeader}>
                        {(Platform.OS === 'android') && (<Image source={images.header} style={styles.modalHeaderBG} blurRadius={1}/>)}
                        <TouchableOpacity onPress = {() => this.setState({protestoIsOpen:false})} style={styles.downModalBtn} >
                        <Image source={images.downModal} style={styles.downModalImg} />
                        </TouchableOpacity>
                        <BlurView
                            style={styles.modalHeader}
                            viewRef={this.state.viewRef}
                            blurType="dark"
                            blurAmount={10}
                        />
                    </View>
                        <ContainerPendencias screenProps={{tipo:'Protesto'}}  ref={navigatorRef => {
                            NavigationService.setTopLevelNavigator(navigatorRef);
                        }}/>
                </Modal>
```

**Comment by rewieer** [comment] 2019-03-20 16:31
I will try your code when I have some time for it, see if it also flickers on my emulator.

**Comment by mmazzarolo** [comment] 2019-03-20 17:10
Hey 👋  could you please provide a small repository for testing the issue?

**Comment by rewieer** [comment] 2019-03-22 16:07
@P21Marcelo @jake41 you guys use the same animation in and out. This is probably the cause of the flicker.
Can you try to fix it and tell me if it still flickers ?

**Closed** 2019-03-22 16:08 UTC

**Comment by jake41** [comment] 2019-03-22 16:53
@rewieer  Yup, it worked for me, changed it to :

`      animationIn="fadeIn"
        animationOut="fadeOut"`

**Comment by iksent** [comment] 2019-03-28 08:31
I am having same issue with this code:

```

**Comment by dblommesteijn** [comment] 2019-05-13 13:12
Here too, It looks like there is a flicker in the `backdrop`. I'm running `react-native-modal@^11.0.0` with `react-native@0.59.2`.

**Comment by LaVielle** [comment] 2019-05-15 10:46
I fixed the flickering problem by setting the <Modal> to always visible:
```
// MyModalComponent.js
<Modal
        isVisible // always true
        animationIn="fadeIn"
        animationOut="fadeOut"
        onBackButtonPress={onBackButtonPress}
        onBackdropPress={onBackdropPress}
        useNativeDriver
>
        // content
</Modal>
```

So instead of making the isVisible prop true/false based on state or props, I mount/unmount the whole modal in the parent component, achieving the same effect, without the flickering problem:

```
// Parent.js
{showModal &&
        <MyModalComponent>
}
```

**Comment by pontigol** [comment] 2019-05-17 14:00
For what it's worth, I had the same issue and to me it seems connected to the backdrop as @dblommesteijn mentioned. I tried all of the above and nothing worked but then **I tried setting `backdropTransitionOutTiming={0}` and it solved it** for me. It probably affects the look of the out animation but I think it looks good and the flicker is gone.

**Comment by alamothe** [comment] 2019-05-19 11:27
I filed a new issue: https://github.com/react-native-community/react-native-modal/issues/310

Having the same problem with backdrop flashes. I'm using the default `"slideOutDown"` though.

**Comment by alamothe** [comment] 2019-05-19 11:29
WOW! Setting `backdropTransitionOutTiming={0}` as suggested by @pontigol solves the issue. It does not affect animation at all for me.

**Comment by N1ghtly** [comment] 2019-05-22 06:28
I can confirm that @pontigol's solution works for me as well.

**Comment by dblommesteijn** [comment] 2019-05-22 11:48
I can confirm that @pontigol's solution works for me as well. Adding the `backdropTransitionOutTiming={0}` property and value. Great job!

**Comment by arelstone** [comment] 2019-07-16 07:05
For me adding `backdropTransitionOutTiming={0}` did not solve the issue. Adding `hideModalContentWhileAnimating` did solve it.

Thanks guys 👍

**Comment by mounthorse-slns** [comment] 2019-07-26 11:48
`backdropTransitionOutTiming={0}` solves for me

**Comment by immint023** [comment] 2019-08-16 15:38
> For what it's worth, I had the same issue and to me it seems connected to the backdrop as @dblommesteijn mentioned. I tried all of the above and nothing worked but then **I tried setting `backdropTransitionOutTiming={0}` and it solved it** for me. It probably affects the look of the out animation but I think it looks good and the flicker is gone.

it's work for me, thanks so much

**Comment by franzwarning** [comment] 2019-09-11 21:36
`backdropTransitionOutTiming={0}` solves for me... but does anyone know why?? haha

**Comment by nabinbhusal80** [comment] 2019-10-02 03:28
backdropTransitionOutTiming={0} this will solve the problem whatever the animationType you use. This is because the flickering is caused by the backdrop.

**Comment by mmazzarolo** [comment] 2019-10-02 07:26
FYI I recently worked on a simple backdrop animation using react-native's own modal and [the issue is still here](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/c9d8443374f13696e9ce70a48e36da0e1dc36d11/src/Modal.js#L78).  
I'm not sure why it's happening but the native driver seems to have some issues in the modal context.

**Comment by mmazzarolo** [comment] 2019-10-02 07:28
Probably related to: https://github.com/facebook/react-native/issues/21552

**Comment by junix13** [comment] 2019-10-09 07:06
> For what it's worth, I had the same issue and to me it seems connected to the backdrop as @dblommesteijn mentioned. I tried all of the above and nothing worked but then **I tried setting `backdropTransitionOutTiming={0}` and it solved it** for me. It probably affects the look of the out animation but I think it looks good and the flicker is gone.

It worked! Thank you so much!

**Comment by ElegantSoft** [comment] 2020-07-05 19:52
> I can confirm that @pontigol's solution works for me as well. Adding the `backdropTransitionOutTiming={0}` property and value. Great job!
> 
> **Addition (29-May-2019):** I ran into issues with flickering again. This time on fadeOut, the entire container reappears after it's faded out. Setting prop: `hideModalContentWhileAnimating` helps to solve this.

it works perfectly to me

**Comment by noushad-techconfer** [comment] 2021-02-05 07:40
use useNativeDriver

**Comment by ethanwc** [comment] 2021-02-10 00:00
For me I was re rendering too much causing the flickering so I wrapped my list component in useMemo hook.

**Comment by ALPOFF** [comment] 2021-04-20 17:57
> WOW! Setting `backdropTransitionOutTiming={0}` as suggested by @pontigol solves the issue. It does not affect animation at all for me.

and me too, thank you

**Comment by bosz** [comment] 2021-07-03 08:42
I used `backdropTransitionOutTiming={0}` and the flickering effect stopped.

**Comment by qnrjs42** [comment] 2022-02-16 08:02
react-native: 0.66.4
react-native-modal: 13.0.0

Correct

```
<Modal
  isVisible={isModal}
  onBackdropPress={() => setIsModal(false)}
  useNativeDriver
  hideModalContentWhileAnimating
>
  <View
    style={{
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'white',
      padding: 22,
    }}
  >
    <Text>Hello react-native-modal</Text>
  </View>
</Modal>
```

**Comment by charbelmansour005** [comment] 2023-02-01 21:12
> I can confirm that @pontigol's solution works for me as well. Adding the `backdropTransitionOutTiming={0}` property and value. Great job!
> 
> **Addition (29-May-2019):** I ran into issues with flickering again. This time on fadeOut, the entire container reappears after it's faded out. Setting prop: `hideModalContentWhileAnimating` helps to solve this.

Worked for me, **February 1 2023**

**Comment by baez97** [comment] 2023-02-23 10:36
I thought setting the `backdropTransitionOutTiming` to 0 would remove the backdrop animation so it would look weird, but it didn't affect at all. Both the modal and the backdrop are animated, so it solved the problem without any cons.
Thank you! @charbelmansour005 @pontigol !

**Comment by charbelmansour005** [comment] 2023-02-23 19:02
> I thought setting the `backdropTransitionOutTiming` to 0 would remove the backdrop animation so it would look weird, but it didn't affect at all. Both the modal and the backdrop are animated, so it solved the problem without any cons.
> Thank you! @charbelmansour005 @pontigol !

No problem!

**Comment by yuriifaievskyi** [comment] 2023-08-18 13:18
great! Thanks! `backdropTransitionOutTiming={0}` fixed problem with blinking on android for me

**Comment by ZackOfAllTrades** [comment] 2024-08-02 16:03
this still happens on react-native-modal": "^13.0.1"

**Comment by imalgrab** [comment] 2024-10-04 08:13
> this still happens on react-native-modal": "^13.0.1"

Have you tried @yuriifaievskyi solution? Try setting `backdropTransitionOutTiming={0}` - it solved the issue for me

**Comment by AkramHarazem** [comment] 2024-10-26 15:42
me too, still happens on react-native-modal": "^13.0.1"

**Comment by gabrielew** [comment] 2024-12-04 13:50
with `backdropTransitionOutTiming={0}` doesn't work, but
`backdropTransitionOutTiming={1}` solved the problem here.

**version: "^13.0.1"**

```tsx
<Modal
  isVisible={showModal}
  onBackdropPress={handleOnClose}
  animationIn="slideInUp"
  animationOut="slideOutDown"
  renderToHardwareTextureAndroid
  animationInTiming={300}
  animationOutTiming={300}
  backdropTransitionOutTiming={1}
  backdropColor={theme.color.gray["064"]}
  style={{ margin: 0 }}>  
  // your code  
</Modal>
```

**Comment by narenjaat** [comment] 2024-12-19 17:37
backdropTransitionOutTiming={1} solved the problem here.
<Modal
      coverScreen={true}
      useNativeDriver={false}
      backdropTransitionOutTiming={1}
      hideModalContentWhileAnimating
      isVisible={visible}
      backdropOpacity={0.5}
      onDismiss={onClose}
      style={{ margin: 0 }}
      >

**Comment by ronaldaraujo** [comment] 2024-12-29 20:51
I've tried various combinations of props, but none have worked. What's more, I used exactly what is written in the [readme](https://github.com/react-native-modal/react-native-modal?tab=readme-ov-file#the-modal-flashes-in-a-weird-way-when-animating) but to no success :/

https://github.com/user-attachments/assets/a2d9ca07-bcff-4287-8274-2c154017e106

**Comment by Dat-Mobile** [comment] 2025-01-09 17:05
```
backdropTransitionOutTiming={1} solved the problem here.
```
It's true. What the heck just happen here 😆
I also added backdropTransitionInTiming={0} and it's so smooth now

**Comment by arian-fallahpour** [comment] 2025-02-01 04:52
When I used `backdropTransitionOutTiming={1000}` and `backdropTransitionInTiming={1000}` it stopped flickering, and the modal stopped having a weird glitch where the previous content would show.

**Comment by NameHitherto** [comment] 2025-03-21 15:37
I feel that my luck is not very good, I tried the methods above and I feel that the animation is still not silky smooth, not only the flickering of the backdrop, but also the flickering of the text in the status bar, the abrupt flickering of the elements inside the Modal and so on, it is really hard to use.
```
<StatusBar 
        backgroundColor={colors.header}
        barStyle='dark-content'
      />
...
<Modal
            isVisible={isBottomSheetVisible}
            onBackButtonPress={toggleBottomSheet}
            onBackdropPress={toggleBottomSheet}
            backdropOpacity={0.3}
            statusBarTranslucent={true}
            deviceHeight={Dimensions.get('screen').height}
            animationIn={'slideInUp'}
            animationOut={'slideOutDown'}
            useNativeDriver={false}
            backdropTransitionOutTiming={1}
            hideModalContentWhileAnimating={true}
            style={{justifyContent: 'flex-end'}}
          >
...
</Modal>
```

**Comment by Ozaoujal** [comment] 2025-03-26 03:56
The issue still exists, hiding the backdrop animation is not the solution in my case :(

**Comment by Nebula-Developer** [comment] 2025-04-12 02:53
None of these solutions besides `backdropTransitionOutTiming={1}` fixed it for me, but that removes the fade animation of the backdrop. Has it really been 6 years since this issue appeared?

**Comment by tmoran-stenoa** [comment] 2025-04-15 23:15
This worked for me: https://github.com/react-native-modal/react-native-modal/issues/785. No need to remove the backdrop animation nor change any of the native driver props!

**Comment by VibolSovichea** [comment] 2025-05-09 01:14
> **backdropTransitionOutTiming={1}** _solved the problem for me._ <Modal coverScreen={true} useNativeDriver={false} backdropTransitionOutTiming={1} hideModalContentWhileAnimating isVisible={visible} backdropOpacity={0.5} onDismiss={onClose} style={{ margin: 0 }} >

This work perfectly for me.

**Comment by fDirham** [comment] 2025-06-06 18:14
Couldn't get flickering to stop consistently, decided to just roll my own solution with react native reanimated.

**Comment by DhananjayHirey** [comment] 2025-07-03 12:34
just drop the idea i switched to view and reanimated :)

**Comment by aroshanzamir** [comment] 2025-07-22 07:43
This worked for me:


`            <Modal
                isVisible={isModalVisible}
                animationIn="zoomIn"
                animationOut="zoomOut"
                animationInTiming={500}
                hideModalContentWhileAnimating={true}
                backdropTransitionInTiming={1}
                backdropTransitionOutTiming={1}
                backdropOpacity={0.40}>
                <View style={{ backgroundColor: "#fff", padding: 15, borderWidth: 1, borderColor: "red" }}>
                    <Text>Hello!</Text>

                    <Button title="Hide modal" onPress={toggleModal} />
                </View>
            </Modal>`

**Comment by usmankhan002011** [comment] 2025-08-26 08:17
React 18.3.1

```
<Modal
  isVisible={isModalVisible}
  onBackdropPress={() => setIsModalVisible(false)}
  hideModalContentWhileAnimating={true}
  backdropTransitionOutTiming={1}
  style={styles.modal}
>
```

This solved it for me

**Comment by maik-emanoel** [comment] 2025-09-03 15:07
> with `backdropTransitionOutTiming={0}` doesn't work, but `backdropTransitionOutTiming={1}` solved the problem here.
> 
> **version: "^13.0.1"**
> 
> <Modal
>   isVisible={showModal}
>   onBackdropPress={handleOnClose}
>   animationIn="slideInUp"
>   animationOut="slideOutDown"
>   renderToHardwareTextureAndroid
>   animationInTiming={300}
>   animationOutTiming={300}
>   backdropTransitionOutTiming={1}
>   backdropColor={theme.color.gray["064"]}
>   style={{ margin: 0 }}>  
>   // your code  
> </Modal>

This workaround solved my problem with flickering. Thanks man!

**Comment by lapidcj** [comment] 2025-09-24 17:30
> with `backdropTransitionOutTiming={0}` doesn't work, but `backdropTransitionOutTiming={1}` solved the problem here.
> 
> **version: "^13.0.1"**
> 
> <Modal
>   isVisible={showModal}
>   onBackdropPress={handleOnClose}
>   animationIn="slideInUp"
>   animationOut="slideOutDown"
>   renderToHardwareTextureAndroid
>   animationInTiming={300}
>   animationOutTiming={300}
>   backdropTransitionOutTiming={1}
>   backdropColor={theme.color.gray["064"]}
>   style={{ margin: 0 }}>  
>   // your code  
> </Modal>


this fixed my issue

**Comment by Alwaysdebugg** [comment] 2026-03-12 21:50
> ```
> backdropTransitionOutTiming={1} solved the problem here.
> ```
> 
> It's true. What the heck just happen here 😆 I also added backdropTransitionInTiming={0} and it's so smooth now

That works for me, Thx
