### ISSUE TITLE
Can't not find Variable:requireNativeComponent.

### ISSUE THREAD

**Issue by Jeijie** [react-native-community/react-native-modal#276] opened 2019-03-26 09:41 UTC
an error occurred when  I run react-native run-android.

 "react-native-modal": "^9.0.0",

![image](https://user-images.githubusercontent.com/9338052/54986772-3b775d80-4fee-11e9-9053-fa7744bc3439.png)

React Native Environment Info:
  System:
    OS: Windows 7
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    Memory: 11.15 GB / 15.88 GB
  Binaries:
    Node: 8.12.0 - F:\install\nodejs\node.EXE
    Yarn: 1.9.4 - C:\Users\GDYT\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - F:\install\nodejs\npm.CMD

**Comment by rewieer** [comment] 2019-03-26 09:57
Your sourcemaps are probabled wrong as we don't use any native component and, therefore, don't make such calls.
It's much likely an other file is the origin of the error, you should check the exact line in your debugger to find a culprit.

Closing for the moment.

**Closed by rewieer** 2019-03-26 09:57 UTC

**Comment by cvarley100** [comment] 2019-04-30 10:05
@rewieer Facing the same issue on an upgrade to 59.5. An old `Modal.js` file is added when running yarn.

**Comment by rewieer** [comment] 2019-04-30 14:26
We are depending on react-native as a `peer dependency` which means that when you download `react-native-modal` it doesn't have a `react-native` folder it in `node_modules`. 
I don't think we can do anything about it because that's a weird error (I admit I had it at least once). But if there's to be a culprit it's either `react-native` or `metro`.

**Comment by rajivshah3** [comment] 2019-07-16 18:34
For us this turned out to be caused by https://github.com/listenzz/react-native-modal-translucent/issues/21, not `react-native-modal`

**Comment by pablobrodt** [comment] 2019-08-12 19:41
I updated react-native-modal-translucent to version 3.0.1, removed node_modules and package-lock.json, cleaned npm cache and reinstalled the whole s*** again. Worked fine.
